name: panic
description: Terminate the Flutter app immediately.
version: 0.0.1
homepage: https://github.com/minikin/panic.git

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter