name: panic
description: Terminate the Flutter app immediately.
version: 0.1.0
homepage: https://github.com/minikin/panic.git

environment:
  sdk: ">=2.13.3 <3.0.0"
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter